services:
  - type: web
    name: achados-perdidos
    env: php
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader && npm install && npm run build && php artisan storage:link && php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: achados-perdidos
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: achados-perdidos-db
          property: connectionString
      - key: FILESYSTEM_DISK
        value: public
      - key: CHATIFY_MESSENGER_COLOR
        value: "#1976D2"
      - key: CHATIFY_STORAGE_DISK
        value: public

databases:
  - name: achados-perdidos-db
    plan: free
